# Generated by Django 4.2.6 on 2023-11-02 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_remove_user_username_user_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('moder', 'Moderator'), ('user', 'User')], default='user', max_length=15, verbose_name='Роль'),
        ),
    ]
