# Generated by Django 4.2.6 on 2023-12-07 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='currency',
            field=models.CharField(choices=[('usd', 'usd'), ('rub', 'rub')], default='rub', max_length=20, verbose_name='Валюта'),
        ),
        migrations.AddField(
            model_name='course',
            name='is_buy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Стоимость курса'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='currency',
            field=models.CharField(choices=[('usd', 'usd'), ('rub', 'rub')], default='rub', max_length=20, verbose_name='Валюта'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='is_buy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lesson',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Стоимость урока'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_currency',
            field=models.CharField(choices=[('usd', 'usd'), ('rub', 'rub')], default='rub', max_length=255, verbose_name='Валюта'),
        ),
    ]
